### PR TITLE
update violations in AccessCPS servlet and GalasaGson

### PR DESCRIPTION
**Pull request by KirbyKatcher**
## Why?

This is to fix the cross-site scripting issues in CPS properties and to sanitize the GalasaGson inputs

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]
Looks good thanks!

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
