### PR TITLE
Validate Accept header in all REST endpoints and update OpenAPI docs

### PR DESCRIPTION
**Pull request by eamansour**
## Why?
See https://github.com/galasa-dev/projectmanagement/issues/1925

## Changes
- Lifted up "Accept" header processing from OpenAPI endpoint to the base route class for use by all routes
- Added validation of the "Accept" header to all routes that should have been processing it
  - If an unsupported MIME type is provided in the header, then endpoints will return a 406 Not Acceptable error with an appropriate error message rather than continue to serve a response
- Updated the OpenAPI docs to include the new 406 error response and created common responses that are referenced by REST endpoints to reduce duplication of responses

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by KirbyKatcher — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
