### PR TITLE
Added dev.galasa.framework.api.openapi to hold the yaml file.

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

- Created the new bundle and maven artifact to expose the openapi.yaml file.
- Left the original in-place so that we can push this branch and it won't break any automation until that's changed.
- Deleting the openapi.yaml from its' original location is needed later once everything is using the new bundle.
- We need a successful build of the bundle before anything can depend on it.

It creates content in maven local repo like this:
```
dev.galasa.framework.api.openapi
├── 0.31.0
│   ├── dev.galasa.framework.api.openapi-0.31.0-javadoc.jar
│   ├── dev.galasa.framework.api.openapi-0.31.0-sources.jar
│   ├── dev.galasa.framework.api.openapi-0.31.0.jar
│   ├── dev.galasa.framework.api.openapi-0.31.0.module
│   ├── dev.galasa.framework.api.openapi-0.31.0.pom
│   └── dev.galasa.framework.api.openapi-0.31.0.yaml
└── maven-metadata-local.xml
```

The .yaml file is the spice in this story.
The fact that the jar is created, but empty, is fine.
Later on we will add code which allows the servlet layer to get the resource from this bundle so it can serve it up on an api endpoint.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-481-pm7ms for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-481-tsxb6 for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-481-jqk9g for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
