### PR TITLE
Update release.yaml using the auto-generated release.yaml during local builds

### PR DESCRIPTION
**Pull request by eamansour**
## Why?
See https://github.com/galasa-dev/projectmanagement/issues/1902

## Changes
- Gradle builds generate a release.yaml based on the versions of all bundles in the framework project, so the build-locally script now copies that file into the actual release.yaml file, which removes the need to manually update bundle versions in the release.yaml.
- Updated the release.yaml based on the results from running the modified build-locally script

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by techcobweb — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
