### PR TITLE
Build locally with a bash script

### PR DESCRIPTION
**Pull request by techcobweb**
- [x] Lots of javadoc warnings fixed
  - Only 100 left, and all of those are 'no description for parameter' or 'no description for thrown'
- [x] Added `build-locally.sh`

Currently it takes my machine 8 minutes. There must be something wrong as a result.

### CODE REVIEW

**Comment by jadecarino** [comment]
Hi Mike, I have ran your script and I am running into a problem. This is when running with --delta and no overrides.
I have attached the log in a text file as it's quite long. I don't think this is to do with your script, as it's the same error we saw the other day when just running the commands:

```* What went wrong:
Plugin [id: 'dev.galasa.githash', version: '0.15.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'dev.galasa.githash:dev.galasa.githash.gradle.plugin:0.15.0')
  Searched in the following repositories:
    maven(https://galasadev-cicsk8s.hursley.ibm.com/main/maven/obr/)
    maven2(https://repo.maven.apache
[Framework build script output - no overrides.txt](https://github.com/galasa-dev/framework/files/9939525/Framework.build.script.output.-.no.overrides.txt)
.org/maven2/)
    Gradle Central Plugin Repository ```

Not sure if you get the same error or not? It might be good to understand why this happens, as otherwise people who run the script with no overrides will likely get this error.

I am also unsure what the second error is from, right at the bottom of the log the last 5 lines. Have you seen that one?

**Comment by jadecarino** [comment]
[Framework build script output - no overrides.txt](https://github.com/galasa-dev/framework/files/9939578/Framework.build.script.output.-.no.overrides.txt)

**Review by jadecarino — APPROVED** [review]
Happy for you to merge this in, I just wanted to comment the above as this issue might need addressing in general as it commonly occurs.

**Comment by techcobweb** [comment]
> Happy for you to merge this in, I just wanted to comment the above as this issue might need addressing in general as it commonly occurs.

Is it raised as an issue yet ?

**Comment by jadecarino** [comment]
Lets chat on Monday, if you haven't seen this it might be an issue my end. If not, I'll raise an issue for it.

**Pull request merged**
