### PR TITLE
1938 - Reduced logging when searching for a file to download.

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

# Why ?
See https://github.com/galasa-dev/projectmanagement/issues/1938

### CODE REVIEW

**Comment by techcobweb** [comment]
@jadecarino Could it be as simple as this ?

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-608-g8xx8 for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]
Yes it certainly looks like it - approved

**Pull request merged**
