### PR TITLE
framework.manifest maven artifacts created so OBR can download dependencies via maven.

### PR DESCRIPTION
**Pull request by Akyiaa**
- Metadata about each bundle now sits in the `build.gradle` file within that bundle's build process.
- The overall parent project causes that metadata to be rendered into a release.yaml file
- The `release.yaml` file has two 'groups' of bundles: `framework` and `api`
- That `release.yaml` file is published to maven as artifact `dev.galasa/dev.galasa.framework.manifest`
- The new bundle has the same version number as the framework bundle.
  - `set-version.sh` script updated to keep the two in step.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by techcobweb — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
