### PR TITLE
Added log generation/uploading

### PR DESCRIPTION
**Pull request by jaydee029**
For issue galasa-dev/projectmanagement#1965

### CODE REVIEW

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Review by jadecarino — APPROVED** [review]
Approved for building

**Review by jadecarino — APPROVED** [review]
Approved for building

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]
Approved for building

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
