### PR TITLE
Instructions for developer setup

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

# Why ?

The instructions to set up a development system needed improvement.

Now we have instructions for:
- Running etcd in a docker image
- Running couchdb in a docker image
- Running dex in a docker image
- Running the API server locally
- Running the Web UI locally
- Setting up the CPS
- Setting up the CLI

We also can launch the following using the `run-locally.sh` script:
- etcd
- couchdb
- dex
- api

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by KirbyKatcher — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-610-2mq4c for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-610-sgk6n for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]

**Pull request merged**
