### PR TITLE
Add DELETE /auth/tokens/{tokenid} route to revoke auth tokens

### PR DESCRIPTION
**Pull request by eamansour**
## Why?
See https://github.com/galasa-dev/projectmanagement/issues/1729

## Changes
- Added a new `DELETE /auth/tokens/{tokenid}` route used to revoke auth tokens from the ecosystem using Dex's gRPC API to revoke the refresh token and the associated Dex client, before deleting the record of the token from the ecosystem's auth store
- Updated the OpenAPI docs to include a 404 response from the new endpoint when a token with the given ID does not exist
- Removed early returns in the BaseServlet class when matching servlet routes for improved readability
- Changed `IAuthToken` into `IInternalAuthToken` for use by internal auth token beans (e.g. CouchDBAuthToken in extensions) to store additional information like Dex client IDs that should not be displayed to users via API responses

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by KirbyKatcher — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
