### PR TITLE
mcobbett dev instructions

### PR DESCRIPTION
**Pull request by techcobweb**
# Why ?

Trying to improve the developer experience so running required services in docker images is easier to do, so you can test your api layer easier.

- **check return codes from run-locally.sh script**
- **test-all-locally.md docs improved to talk about the run-locally.sh script**

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
