### PR TITLE
added test files to detect-secrets and audited the secrets

### PR DESCRIPTION
**Pull request by KirbyKatcher**
## WHY?

extension of #558 to add pre-commit hook

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
