### PR TITLE
Temporary fix for local build script pending the better method

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

Temporary fix:
- The dex.proto file is downloaded, but not if it already exists.
- The clean builds never clean it up.
- Need to discuss further with @eamansour about how to make this better later.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]
This works, thanks - happy to discuss better solutions whenever you'd like!

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
