### PR TITLE
Prevent method being added twice when examples are used

### PR DESCRIPTION
**Pull request by hobbit1983**
This PR contributes a fix to this issue: https://github.com/galasa-dev/projectmanagement/issues/1788

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by techcobweb — APPROVED** [review]
Approved, though I would like to see some unit tests which would have demonstrated the problem too.

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
