### PR TITLE
Words matter - Change to the maven plugin for allowlist 

### PR DESCRIPTION
**Pull request by Jimbo4794**

### CODE REVIEW

**Comment by Jimbo4794** [comment]
@Michael-Baylis Can you review this please. Im not familar with how maven plugins work, so unsure if this class name change will impact other repos

**Review by Michael-Baylis — CHANGES_REQUESTED** [review]
Delete the staging project,  dont need it

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Review by Michael-Baylis — APPROVED** [review]

**Pull request merged**
